apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/k8ssandra/cass-operator/config/deployments/cluster?ref=640a4db58314088b1ccee3b8f7db2fb6c90e2f56

components:
  - ../../components/cass-operator-image-config
