
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: k8ssandra-operator
rules:
- apiGroups:
  - k8ssandra.io
  resources:
  - k8ssandraclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: k8ssandra-operator
  namespace: k8ssandra
rules:
- apiGroups:
  - cassandra.datastax.com
  resources:
  - cassandradatacenters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8ssandra.io
  resources:
  - k8ssandraclusters/finalizers
  verbs:
  - update
- apiGroups:
  - k8ssandra.io
  resources:
  - k8ssandraclusters/status
  verbs:
  - get
  - patch
  - update
