
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8ssandra.io.k8ssandra.io
  resources:
  - k8ssandraclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8ssandra.io.k8ssandra.io
  resources:
  - k8ssandraclusters/finalizers
  verbs:
  - update
- apiGroups:
  - k8ssandra.io.k8ssandra.io
  resources:
  - k8ssandraclusters/status
  verbs:
  - get
  - patch
  - update
