name: Run unit and integration tests

on:
  push:
    branches:
      - master

  pull_request:
    branches: [ master ]

jobs:
  testing:
    name: Run unit/integration tests
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.16
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run unit and tests
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          make test
