name: Deploy Image

on:
  push:
    branches:
      - master
      - initial-cassandra

jobs:
  deploy_image:
    needs:
      - unit_integration_tests
      - kind_e2e_tests
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.16
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set git parsed values
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
      - name: Download k8ssandra-operator image
        uses: actions/download-artifact@v2
        with:
          name: k8ssandra-operator
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/k8ssandra-operator-operator.tar
      - name: Tag image
        run: docker tag k8ssandra/k8ssandra-operator:latest k8ssandra/k8ssandra-operator:${{ steps.vars.outputs.sha_short }}
      - name: Push image
        run: |
          docker push k8ssandra/k8ssandra-operator:latest
          docker push k8ssandra/k8ssandra-operator:${{ steps.vars.outputs.sha_short }}